name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-mojo-action@v1
      - name: Run tests
        run: |
          mojo test -I src tests
      - name: Package
        run: |
          mojo package -o textkit.mojopkg src/textkit
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: textkit.mojopkg
          path: textkit.mojopkg
